### ISSUE TITLE
Movement Arrows/Radicals on certain files need fixing

### ISSUE THREAD

**Issue by Hatsune-xMikux** [LastationVRChat/NSFW-GoLoco#11] opened 2024-08-22 23:43 UTC
### Project Version

NSFW Locomotion v1.8.3-NSFW-1.0.0 (Unity 2022 Full) - Possible with other versions haven't checked.

### Describe your issue.

Bugged Files (in Unity with fixes maybe were missed as i see the others have the fixes already implemented) Not sure if it's my end.

Issues that it can cause: Movement not working while in poses.

GoGo/NSFW Locomotion/MainMenu/NSFW/Submenu/NSFW Emotes Menu.asset Fixes:

Change Up Arrow to 126
Change Down Arrow to 127
Change Radical Puppet (one with Friends_noneOnline Icon) to 125

GoGo/NSFW Locomotion/MainMenu/NSFW/Submenu/NSFW Poses Menu.asset Fixes:

Change Up Arrow to 126
Change Down Arrow to 127
Change Radical Puppet (one with Friends_noneOnline Icon) to 125

GoGo/NSFW Locomotion/MainMenu/NSFW/Submenu/Poses/NSFW Poses 2.asset Fixes: 

Change Radical Puppet (one with Friends_noneOnline Icon) to 125

GoGo/NSFW Locomotion/MainMenu/NSFW/Submenu/Poses/NSFW Poses 2+.asset Fixes: 

Change Radical Puppet (one with Friends_noneOnline Icon) to 125

GoGo/NSFW Locomotion/MainMenu/NSFW/Submenu/Poses/NSFW Poses 3.asset Fixes: 

Change Radical Puppet (one with Friends_noneOnline Icon) to 125

GoGo/NSFW Locomotion/MainMenu/NSFW/Submenu/Poses/NSFW Poses 3+.asset Fixes:

Change Radical Puppet (one with Friends_noneOnline Icon) to 125

### Have you modified the project?

No

### Did the issue happen in-game or on Unity Editor?

Unity Editor

**Comment by KuryKat** [comment] 2024-08-24 21:18
Hey there! Thanks for your bug report, we are always welcome to feedback and help!

The thing is, I am a bit confused, could you clarify what the bug is? Because this issue feels more like a suggestion rather than a bug report...

If anything, could you elaborate on:
- What the bug is?
- How to reproduce it?
- Anything else we should know?

We thank you in advance for your time and contributions.

**Comment by KuryKat** [comment] 2024-08-25 00:10
Could you also tell us exactly what Unity version you're using?

**Comment by WillyB1337** [comment] 2024-09-01 01:21
Im getting the same issue.

Basically, were unable to adjust the height while in any of the NSFW poses. It causes the pose to be cancelled.

**Comment by KuryKat** [comment] 2024-09-01 01:29
Ahhh fair enough, we'll look into it!

**Comment by KuryKat** [comment] 2024-09-01 01:30
> Could you also tell us exactly what Unity version you're using?

@WillyB1337  could you also tell me?

**Comment by KuryKat** [comment] 2024-09-01 01:35
I’ve realized what went wrong, and I sincerely apologize for the confusion. I accidentally used the old menu parameters on the new version of Gogoloco, which caused the issue since they were changed in the newer update.

Thanks for catching that, @Hatsune-xMikux !

**Comment by WillyB1337** [comment] 2024-09-01 01:45
its been broken since the GGL 1.8.7 update. Im troubled that it was never found out before 😂

**Comment by KuryKat** [comment] 2024-09-01 01:51
> its been broken since the GGL 1.8.7 update. Im troubled that it was never found out before 😂

🤔🤔 Sorry, 1.8.7 ?

But Latest GoGo Loco is 1.8.3

**Comment by WillyB1337** [comment] 2024-09-01 01:53
I meant 1.8.1 my b

**Comment by KuryKat** [comment] 2024-09-01 01:54
> I meant 1.8.1 my b

Oh that's okay! Thanks for clarifying! And yeah the project was on hold ever since then, I only recently took it over and now we're back into maintaining it, that's why it wasn't fixed!

**Comment by KuryKat** [comment] 2024-09-01 02:32
Issue fixed! It will be available in the next release. Stay tuned for when it comes out!

**Comment by WillyB1337** [comment] 2024-09-01 21:44
> Issue fixed! It will be available in the next release. Stay tuned for when it comes out!

What will be the timeframe of the release?
Will the fix will require any major modifications to the prefab or will it just be a import and upload on existing avatars using it?

**Comment by tw1l1ght** [comment] 2024-09-01 22:16
I did fix mine shorlty after "fixxed in the neXt rls" got announced :)
...impatient as I am I figured the new files sitting in another branch already.

And as its "only" a handful of menu-asset files been changed - dl'ing & replacing the ones in unity was a thing of minutes ;)

AFAI can tell so far its working perfectly fine now <3

**Comment by KuryKat** [comment] 2024-09-02 02:43
> > Issue fixed! It will be available in the next release. Stay tuned for when it comes out!
> 
> What will be the timeframe of the release? Will the fix will require any major modifications to the prefab or will it just be a import and upload on existing avatars using it?

As soon as possible, and you'll only need to re-import the new version, and the files will be updated. The Prefabs will stay the same.

We are working on a major update soon, which will bring an easier way to install, update and manage your installation of NSFW Locomotion! Stay tuned! ✨💥

**Comment by KuryKat** [comment] 2024-09-04 00:18
This issue has been fixed by [v1.0.1](https://github.com/LastationVRChat/NSFW-Locomotion/releases/tag/v1.8.3-NSFW-1.0.1) which was just rolled out today! Make sure to update your projects and report any new bugs in [here](https://github.com/LastationVRChat/NSFW-Locomotion/issues/new)!

**Closed as completed** 2024-09-04 00:19 UTC
Labels: Bug 🐛, Status: Fixed In Next Release, Priority: Medium, Unity 2022, Unity 2019

**Comment by WillyB1337** [comment] 2024-09-22 16:02
Hello there. I believe some poses are still breaking when using the height radial.

I will provide footage in a bit.

**Comment by WillyB1337** [comment] 2024-09-23 02:07
Everthing in Poses 2

**Comment by KuryKat** [comment] 2024-09-27 16:45
> Hello there. I believe some poses are still breaking when using the height radial.
> 
> I will provide footage in a bit.

Yes please send us some more information, please.

**Comment by WillyB1337** [comment] 2024-10-20 17:53
@Hatsune-xMikux, Have your issues been fixed?
Talking about what you initially posted 

> Issues that it can cause: Movement not working while in poses.
> 
> GoGo/NSFW Locomotion/MainMenu/NSFW/Submenu/NSFW Emotes Menu.asset Fixes:
> 
> Change Up Arrow to 126
> Change Down Arrow to 127
> Change Radical Puppet (one with Friends_noneOnline Icon) to 125
> 
> GoGo/NSFW Locomotion/MainMenu/NSFW/Submenu/NSFW Poses Menu.asset Fixes:
> 
> Change Up Arrow to 126
> Change Down Arrow to 127
> Change Radical Puppet (one with Friends_noneOnline Icon) to 125
> 
> GoGo/NSFW Locomotion/MainMenu/NSFW/Submenu/Poses/NSFW Poses 2.asset Fixes:
> 
> Change Radical Puppet (one with Friends_noneOnline Icon) to 125
> 
> GoGo/NSFW Locomotion/MainMenu/NSFW/Submenu/Poses/NSFW Poses 2+.asset Fixes:
> 
> Change Radical Puppet (one with Friends_noneOnline Icon) to 125
> 
> GoGo/NSFW Locomotion/MainMenu/NSFW/Submenu/Poses/NSFW Poses 3.asset Fixes:
> 
> Change Radical Puppet (one with Friends_noneOnline Icon) to 125
> 
> GoGo/NSFW Locomotion/MainMenu/NSFW/Submenu/Poses/NSFW Poses 3+.asset Fixes:
> 
> Change Radical Puppet (one with Friends_noneOnline Icon) to 125

**Comment by KuryKat** [comment] 2024-10-21 03:33
Yeah, those issues should be fixed, the issue was that those buttons weren't working
