### ISSUE TITLE
Deuzear hands bend weird

### ISSUE THREAD

**Issue by konn-neko** [LastationVRChat/NSFW-GoLoco#17] opened 2024-12-03 11:30 UTC
### The project version

1.1.1

### Which Unity Version are you using?

2022.3.22f1

### Describe your issue.

On the deuzear, i noticed it gives ut the ability to give middle finger, i like that part, but the fingers bend weirdly
![image](https://github.com/user-attachments/assets/57115a97-f348-4457-8be5-7473bb950627)
![image](https://github.com/user-attachments/assets/6eb93193-f56e-49e6-9546-0c61e51c98cf)

### Steps to reproduce the problem:

```bash
1.add loco
2.build
3.test, and results
...
```

### Have you modified the project?

No

### Did the issue happen in-game or on Unity Editor?

Both

**Comment by KuryKat** [comment] 2024-12-03 21:55
That seems to be an issue on how the avatar hand bones are defined, and not an issue on our side, the middle finger animation expects humanoid bones, if the avatar uses different bone format, or the order of bones is wrong, it can cause this issue.

Please check your bone structure for a fix, perhaps contact the avatar creator for support.

I'll close this issue since this is not a bug on our end.

**Closed as not planned** 2024-12-03 21:55 UTC
Labels: Support 😵‍💫, Unity 2022
